version: '3.8'

services:
  tutox-sms-nginx:
    image: nginx:latest
    container_name: tutox-sms-nginx
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    restart: "always"
    networks:
      - "tutox-sms-net"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    networks:
      - "tutox-sms-net"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  nginx-conf:
  certbot-etc:
  certbot-var:
  webroot:


networks:
  tutox-sms-net:
    external: true
