services:
  tutox-sms-nginx:
    image: nginx:latest
    container_name: tutox-sms-nginx
    restart: "always"
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "tutox-sms-net"

networks:
  tutox-sms-net:
    external: true
